
#define TOTALACTION			10

#define OBJECTSTOP			0
#define OBJECTMOVE			1
#define OBJECTRUN			2
#define OBJECTATTACK		3
#define OBJECTMAGIC			4
#define OBJECTGETITEM		5
#define OBJECTDAMAGE		6
#define OBJECTDAMAGEMOVE	7
#define OBJECTATTACKMOVE	8
#define OBJECTDYING			10			   
#define OBJECTNULLACTION	100

#define OBJECTMOVE_CONFIRM				1001
#define OBJECTMOVE_REJECT				1010
#define OBJECTMOTION_CONFIRM			1020
#define OBJECTMOTION_ATTACK_CONFIRM		1030
#define OBJECTMOTION_REJECT				1040


