
#define INDEX4_MSGID			0
#define INDEX2_MSGTYPE			4

/*
#define INDEX2_LOCX				6
#define INDEX2_LOCY				8
#define INDEX2_OBJECTTYPE		10
#define INDEX1_DIR				12
#define INDEX2_APPEARANCE1		23
#define INDEX2_APPEARANCE2		25
#define INDEX2_APPEARANCE3		27
#define INDEX2_APPEARANCE4		29
#define INDEX2_STATUS			31
#define INDEX2_VALUE1			33
#define INDEX2_VALUE2			35
#define INDEX2_VALUE3			37

#define INDEX20_COMMAND_STRING	13
#define INDEX2_COMMAND_V1		13
#define INDEX2_COMMAND_V2		15		 
#define INDEX2_COMMAND_V3		17
#define INDEX2_COMMAND_V4		19

#define INDEX2_COMMON_VALUE1	10
#define INDEX2_COMMON_VALUE2	12
#define INDEX2_COMMON_VALUE3	14

#define INDEX10_NAME			13
#define INDEX10_CHATNAME		10

#define INDEXX_MOVEMAPDATA		13 //33
#define INDEX10_MAPNAME			33
#define INDEXX_INITMAPDATA		43
#define INDEXX_CHATMSG			20

#define INDEX10_INIT_CHARNAME		6
#define INDEX10_INIT_ACCNTNAME		16
#define INDEX10_INIT_ACCNTPASSWORD	26
#define INDEX20_INIT_GUILDNAME		36
#define INDEX50_INIT_EMAILADDR		36
#define INDEXXX_INIT_PLAYERDATA		36
#define INDEX16_INIT_ADDRESS		26
#define INDEX2_INIT_PORT			42
#define INDEX1_INIT_TOTALMAPS		44
#define INDEXX_INIT_MAPLIST			45

#define INDEX1_INIT_TOTALCHARACTERS	6
#define INDEX1_INIT_ACCOUNTSTATUS	16
#define INDEXX_INIT_CHARACTERINFO	17
#define INDEX1_INIT_GUILDSTATUS		17
#define INDEX1_INIT_GUILDSMANNUM	18

#define INDEXX_INIT_NOTIFYINFO		6
#define INDEX1_INIT_TOTALITEMS		6
#define INDEXX_INIT_ITEMCONTENTS	7

#define INDEX4_INIT_HITPOINT		6
#define INDEX4_INIT_ARMORCLASS		10
#define INDEX4_INIT_THAC0			14
#define INDEX4_INIT_LEVEL			18
#define INDEX4_INIT_STR				22
#define INDEX4_INIT_INT				26
#define INDEX4_INIT_VIT				30
#define INDEX4_INIT_DEX				56
#define INDEX4_INIT_MAG				60
#define INDEX4_INIT_EXP				64
#define INDEX4_INIT_CHARISMA		68
#define INDEX4_INIT_GUILDRANK		72
*/
