
enum skillIndexes
{
	SKILL_0,	
	SKILL_AGILITY,		
	SKILL_PRAYER,			
	SKILL_MINING,			
	SKILL_MANUFACTURING,	
	SKILL_FISHING,			
	SKILL_FARMING,			
	SKILL_ALCHEMY,	
	SKILL_CRAFTING,
	SKILL_SUMMONING,
	SKILL_PRETENDCORPSE	
};